apiVersion: v1
kind: Service
metadata:
  name: einfchips-welcome-page-service
  labels:
    app: einfchips-welcome-page
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30001  # You can change this if necessary
  selector:
    app: einfchips-welcome-page
